#!/bin/sh

#  Copyright (c) 2006  Volker Grabsch <volker-ad@v.notjusthosting.com>
#
#  Permission is hereby granted, free of charge, to any person obtaining
#  a copy of this software and associated documentation files (the
#  "Software"), to deal in the Software without restriction, including
#  without limitation the rights to use, copy, modify, merge, publish,
#  distribute, sublicense, and/or sell copies of the Software, and to
#  permit persons to whom the Software is furnished to do so, subject
#  to the following conditions:
#
#  The above copyright notice and this permission notice shall be
#  included in all copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


# syntax check
#

if test -z "$1" -o -z "$2" -o -z "$3" -o -z "$4"
then
    VERSION="1.0"
    DESCRIPTION="Create Debian packages out of ZIP and TAR files using alien."
    echo
    echo "    any2deb - $VERSION"
    echo "    ============="
    echo
    echo "$DESCRIPTION"
    echo
    echo
    echo "Syntax:"
    echo "    $0 <package> <version> <source> <prefix> [<alien options>]"
    echo
    echo "Requires:"
    echo "    fakeroot, alien, findutils, [unzip, tar, gzip, bzip2]"
    echo
    echo "Examples:"
    echo "    $0 mingw32-zlib 1.2.3 zlib-1.2.3-lib.zip /usr/i586-mingw32msvc"
    echo
    echo "    $0 mplayer-codecs-essential 20050412 \\"
    echo "        essential-20050412.tar.bz2 /usr/lib/codecs --fixperms"
    echo
    echo "    $0 any2deb $VERSION any2deb.tar /usr/bin -d -r --description \\"
    echo "        \"$DESCRIPTION\""
    echo
    exit 1
fi


# read parameters
#

PACKAGE="$1"
VERSION="$2"
SOURCE="$3"
PREFIX="./$4"

shift 4  # alien options are now in $@

BUILD="build-$PACKAGE"
TGZPACKAGE="$PACKAGE-$VERSION.tgz"


# initialize build folder
#

rm -rf "$BUILD"
mkdir "$BUILD"
mkdir "$BUILD/source"
mkdir "$BUILD/dest"


# unpack source package
#

case "$SOURCE" in
    *.zip)
        unzip "$SOURCE" -d "$BUILD/source"
        ;;
    *.tar)
        tar -xv -f "$SOURCE" -C "$BUILD/source"
        ;;
    *.tgz|*.tar.gz)
        tar -xvz -f "$SOURCE" -C "$BUILD/source"
        ;;
    *.tar.bz2)
        tar -xvj -f "$SOURCE" -C "$BUILD/source"
        ;;
    *)
        echo "unsupported file extension of source archive:"
        echo "    $SOURCE"
        exit 1
        ;;
esac


# determine real source folder
#

BUILD_SOURCE="$BUILD/source"
SUBDIRS=`find "$BUILD_SOURCE" -type d -mindepth 1`
if test -n "$SUBDIRS" -a "`echo "$SUBDIRS" | wc -l`" = 1
then
    BUILD_SOURCE="$SUBDIRS"
fi


# build destination tree
#

BUILD_DEST="$BUILD/dest/$PREFIX"
mkdir -p "$BUILD_DEST"
rmdir "$BUILD_DEST"
mv "$BUILD_SOURCE" "$BUILD_DEST"


# build debian package
#

tar -cvz --owner=root --group=root -f "$BUILD/$TGZPACKAGE" -C "$BUILD/dest" .
fakeroot alien "$@" "$BUILD/$TGZPACKAGE"


# remove build folder
#

rm -rf "$BUILD"
