#!/bin/sh

#  Copyright (c) 2006  Volker Grabsch <volker-ad@v.notjusthosting.com>
#
#  Permission is hereby granted, free of charge, to any person obtaining
#  a copy of this software and associated documentation files (the
#  "Software"), to deal in the Software without restriction, including
#  without limitation the rights to use, copy, modify, merge, publish,
#  distribute, sublicense, and/or sell copies of the Software, and to
#  permit persons to whom the Software is furnished to do so, subject
#  to the following conditions:
#
#  The above copyright notice and this permission notice shall be
#  included in all copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


# syntax check
#

[ "$2" ] || {
cat <<EOF

    debuild-cross - 1.2
    ===================

Cross compile a Debian source package.


Requires:
    dpkg-dev, fakeroot, sed

Syntax:
    debuild-cross <debsrc-pkgname> <arch> [<dpkg-buildpackage options>]

Example:
    debuild-cross smpeg win32 -us -uc

EOF
exit 1
}


# read parameters
#

SOURCE=$1
ARCH=$2

shift 2  # dpkg-buildpackage options are now in $@


# create Debian source directory
#

VERSION=`ls -1 -d "$SOURCE"*/ | sed -n '1 s!^'"$SOURCE"'-\(.*\)/$!\1! p'`
[ "$VERSION" ] || {
    echo "Unable to find the unpacked $SOURCE sources."
    exit 1
}

[ -d "patch-$ARCH-$SOURCE" ] || {
    echo "Unable to find the patch folder: patch-$ARCH-$SOURCE"
    echo "To get started, try debuild-cross-prepare."
    exit 1
}

rm -rf "$ARCH-$SOURCE-$VERSION"
cp -r "$SOURCE-$VERSION" "$ARCH-$SOURCE-$VERSION"
cp -r "patch-$ARCH-$SOURCE"/* "$ARCH-$SOURCE-$VERSION"

[ -f "$ARCH-${SOURCE}_$VERSION.orig.tar.gz" ] || {
    tar -x -f "${SOURCE}_$VERSION.orig.tar.gz"
    mv "$SOURCE-$VERSION.orig" "$ARCH-$SOURCE-$VERSION.orig"
}

cd "$ARCH-$SOURCE-$VERSION"

MAINTAINER=`cat debian/control | sed -n 's/^Maintainer: \(.*\)/\1/p'`
CHANGELOG=`cat debian/changelog`
RELEASE=`echo "$CHANGELOG" | sed -n '1 s/^'"$SOURCE"' (\(.*\)).*/\1/ p'`
cat >debian/changelog <<EOF
$ARCH-$SOURCE ($RELEASE+win32.0) unstable; urgency=low

  * Transform to a $ARCH cross compiling package.

 -- $MAINTAINER  `date -R`

$CHANGELOG
EOF


# build Debian packages
#

dpkg-buildpackage -rfakeroot "$@"


# clean up
#

cd ..
echo "removing: $ARCH-$SOURCE-$VERSION/"
rm -f -r "$ARCH-$SOURCE-$VERSION"
