#!/bin/sh

#  Copyright (c) 2006  Volker Grabsch <vog@notjusthosting.com>
#
#  Permission is hereby granted, free of charge, to any person obtaining
#  a copy of this software and associated documentation files (the
#  "Software"), to deal in the Software without restriction, including
#  without limitation the rights to use, copy, modify, merge, publish,
#  distribute, sublicense, and/or sell copies of the Software, and to
#  permit persons to whom the Software is furnished to do so, subject
#  to the following conditions:
#
#  The above copyright notice and this permission notice shall be
#  included in all copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


# syntax check
#

[ "$5" ] || { cat <<EOF

    gnuwin32-lib2deb - 1.2
    ======================

Download a library from GnuWin32 and
create a Debian package for cross compiling to it.


Requires:
    w3m, wget, dpkg-dev, debhelper, fakeroot, [unzip]

Syntax:
    gnuwin32-lib2deb <pkgname> <deb-pkgname> <full name> <email> \\
                     <sf-mirror> [<dpkg-buildpackage options>]

Example:
    gnuwin32-lib2deb zlib win32-zlib1 "Admin" "root@localhost" \\
                     heanet -b -uc

EOF
exit 1
}


# read parameters
#

PACKAGE=$1
DEBPACKAGE=$2
FULLNAME=$3
EMAIL=$4
SFMIRROR=$5

shift 5  # dpkg-buildpackage options are now in $@

MIRROR=http://$SFMIRROR.dl.sourceforge.net/sourceforge/gnuwin32
HOMEPAGE=http://gnuwin32.sourceforge.net/packages/$PACKAGE.htm
SRCINFO=$PACKAGE-gnuwin32-homepage
DOWNLOAD=http://gnuwin32.sourceforge.net/downlinks/$PACKAGE-lib-zip.php
DLINFO=$PACKAGE-gnuwin32-download.html
PREFIX=usr/i586-mingw32msvc


# download package information
#

echo "downloading: $HOMEPAGE"
wget -nv -O - $HOMEPAGE >$SRCINFO.html || exit 1

echo "converting: $SRCINFO.html -> $SRCINFO.txt"
w3m -dump -cols 70 $SRCINFO.html >$SRCINFO.txt

echo "reading: $SRCINFO.txt"
VERSION=`cat $SRCINFO.txt | sed -n '/^Version$/,$ p' | sed -n 3p`

echo "downloading: $DOWNLOAD"
wget -nv -O - $DOWNLOAD >$DLINFO || exit 1

echo "reading: $DLINFO"
SRCPKG=`cat $DLINFO | sed -n 's!.*"/gnuwin32/\('$PACKAGE-$VERSION'-[^"]*lib\.zip\)".*!\1!p' | sed -n 1p | xargs echo`
RELEASE=`echo $SRCPKG | sed -n 's/'$PACKAGE-$VERSION'-\([^-]\+\)-lib\.zip/\1/p'`
[ "$RELEASE" ] || RELEASE=0
SRCDIR=$DEBPACKAGE-$VERSION

echo "current version of $PACKAGE: $VERSION - GnuWin32 release: $RELEASE"


# download zip package
#

[ -f $SRCPKG ] && {
    echo $SRCPKG alreads exists.
    echo "Nothing to do."
    echo "removing: $SRCINFO.html, $SRCINFO.txt, $DLINFO"
    rm -f $SRCINFO.html $SRCINFO.txt $DLINFO
    exit 0
}

echo "downloading: $MIRROR/$SRCPKG"
wget -nv $MIRROR/$SRCPKG || {
    rm -f $SRCPKG
    exit 1
}


# build deb package
#

echo "removing: $SRCDIR/"
rm -rf $SRCDIR

echo "creating: $SRCDIR/"
mkdir $SRCDIR || exit 1

echo "creating: $SRCDIR/$SRCPKG"
cp $SRCPKG $SRCDIR

echo "creating: $SRCDIR/debian/"
mkdir $SRCDIR/debian

echo "creating: $SRCDIR/debian/changelog"
cat >$SRCDIR/debian/changelog <<EOF
$DEBPACKAGE ($VERSION-${RELEASE}gnuwin32) unstable; urgency=low

  * Initial Release.

 -- $FULLNAME <$EMAIL>  `date -R`

EOF

echo "creating: $SRCDIR/debian/compat"
cat >$SRCDIR/debian/compat <<EOF
4
EOF

echo "creating: $SRCDIR/debian/control"
cat >$SRCDIR/debian/control <<EOF
Source: $DEBPACKAGE
Section: libdevel
Priority: extra
Maintainer: $FULLNAME <$EMAIL>
Build-Depends: debhelper (>= 4.0.0), unzip
Standards-Version: 3.6.1

Package: $DEBPACKAGE-dev
Architecture: all
Depends: mingw32
Description: `cat $SRCINFO.txt | sed -n '/:/,$ {/^$/ q ; s/[^:]*: // ; p}' | xargs echo`
 GnuWin32 port of `cat $SRCINFO.txt | sed -n 5p`
 .
 Package: $SRCPKG
 .
EOF
cat $SRCINFO.txt | sed -n '/^Description$/,$ p' | sed -n '3~1 {/^Homepage$/ q ; s/^$/./ ; s/^/ / ; p}' \
>>$SRCDIR/debian/control
cat >>$SRCDIR/debian/control <<EOF
 Homepage: $HOMEPAGE
EOF

echo "creating: $SRCDIR/debian/copyright"
cat >$SRCDIR/debian/copyright <<EOF
This package was debianized by $FULLNAME <$EMAIL> on
`date -R`.

It was downloaded from: $HOMEPAGE
EOF

echo "creating: $SRCDIR/debian/dirs"
cat >$SRCDIR/debian/dirs <<EOF
$PREFIX
EOF

echo "creating: $SRCDIR/debian/rules"
cat >$SRCDIR/debian/rules <<EOF
#!/usr/bin/make -f
# -*- makefile -*-

UNZIP=unzip

build:
	dh_testdir

clean:
	dh_testdir
	dh_testroot

	dh_clean 

install: build
	dh_testdir
	dh_testroot
	dh_clean -k 
	dh_installdirs

	\$(UNZIP) -d debian/$DEBPACKAGE-dev/$PREFIX $SRCPKG 'include/*'
	\$(UNZIP) -d debian/$DEBPACKAGE-dev/$PREFIX $SRCPKG 'lib/*'
	-\$(UNZIP) -d debian/$DEBPACKAGE-dev/$PREFIX $SRCPKG 'share/*'

binary-indep: build install
	dh_testdir
	dh_testroot
	dh_installchangelogs 
	dh_installdocs
	dh_install
	dh_compress
	dh_fixperms
	dh_installdeb
	dh_gencontrol
	dh_md5sums
	dh_builddeb

binary-arch: build install

binary: binary-indep binary-arch
.PHONY: build clean binary-indep binary-arch binary install
EOF
chmod a+x $SRCDIR/debian/rules

cd $SRCDIR
dpkg-buildpackage -rfakeroot -D "$@" || exit 1
cd ..


# clean up
#

echo "removing: $SRCINFO.html, $SRCINFO.txt, $DLINFO"
rm -f $SRCINFO.html $SRCINFO.txt $DLINFO

echo "removing: $SRCDIR/"
rm -f -r $SRCDIR
